name: 'Cursor Doctor'
description: 'Lint and validate your Cursor AI rules in CI. Catches broken frontmatter, vague instructions, conflicts, and more.'
author: 'nedcodes'
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  path:
    description: 'Path to project root'
    required: false
    default: '.'
  command:
    description: 'Command to run: check (pass/fail) or lint (detailed)'
    required: false
    default: 'check'
runs:
  using: 'composite'
  steps:
    - name: Run cursor-doctor
      shell: bash
      run: npx cursor-doctor@latest ${{ inputs.command }} ${{ inputs.path }}
